//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : �lbum.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class Album {
	private String id;
	private String titulo;
	public Foto contiene;
//	public void new(String titulo) {
	
	//}//
	
/*	public String getTitulo() {

	
	}*/
	
	public void setTitulo(String titulo) {
	
	}
}
