//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Cuidado.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Cuidado {
    public Notificacion esNotificado;
    private String id;
    private Float coste;
    private String fechaInicio;
    private String fechaFin;
    private Boolean pagado;
    private Integer panchoPuntos;
    public Cuidado(Float coste, String fechaInicio, String fechaFin) {
		this.coste = coste;
		this.fechaInicio=fechaInicio;
		this.fechaFin=fechaFin;

    }

    public Float getCoste() {
        return this.coste;
    }

    public void setCoste(Float coste) {
        this.coste = coste;
    }

    public String getFechaInicio() {

        return this.fechaInicio;
    }

    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public String getFechaFin() {

        return this.fechaFin;
    }

    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    public Boolean getPagado() {

        return this.pagado;
    }

    public void setPagado(Boolean pagado) {
        this.pagado = pagado;
    }

    public Integer getPanchoPuntos() {

        return this.panchoPuntos;
    }

    public void setPanchoPuntos(Integer panchoPuntos) {
        this.panchoPuntos = panchoPuntos;
    }

    //Funciones a Implementar
    public Float calcularCoste() {

        return null;
    }

    public Integer calcularPanchoPuntos() {

        return null;
    }
}
