//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Cuidador.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


import java.util.ArrayList;
import java.util.List;

public class Cuidador extends Usuario {
    private final List<Dueno> duenos;
    private String documentacion;
    private String descripcion;
    private Integer distanciaMax;
    private float tarifa;
    private Integer panchoPuntos;
    private String IBAN;
    private String foto;
    private List<Mascota> mascotas;
    private List<MascotaExotica> mascotaExoticas;


    public Cuidador(Integer id, String nombre, String email, String contrasenia, String direccion, String descripcion, Integer distanciaMax, float tarifa, String documentacion, String IBAN, String foto) {
        super(id, nombre, email, contrasenia, direccion);
        this.descripcion = descripcion;
        this.distanciaMax = distanciaMax;
        this.tarifa = tarifa;
        this.documentacion = documentacion;
        this.IBAN = IBAN;
        this.foto = foto;
        this.panchoPuntos = 0;
        this.mascotas = new ArrayList<>();
        this.duenos = new ArrayList<>();
    }

    public Cuidador(String nombre, String email, String contrasenia, String direccion, String descripcion, Integer distanciaMax, float tarifa, String documentacion, String IBAN, String foto) {
        super(nombre, email, contrasenia, direccion);
        this.descripcion = descripcion;
        this.distanciaMax = distanciaMax;
        this.tarifa = tarifa;
        this.documentacion = documentacion;
        this.IBAN = IBAN;
        this.foto = foto;
        this.panchoPuntos = 0;
        this.mascotas = new ArrayList<>();
        this.duenos = new ArrayList<>();
    }

    public List<Mascota> getMascotas() {
        return this.mascotas;
    }

    public void setMascotas(List<Mascota> mascotas) {
        this.mascotas = mascotas;
    }

    public List<MascotaExotica> getMascotaExoticas() {
        return this.mascotaExoticas;
    }

    public void setMascotaExoticas(List<MascotaExotica> mascotaExoticas) {
        this.mascotaExoticas = mascotaExoticas;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getDistanciaMax() {
        return this.distanciaMax;
    }

    public void setDistanciaMax(Integer distanciaMax) {
        this.distanciaMax = distanciaMax;
    }

    public Float getTarifa() {
        return this.tarifa;
    }

    public void setTarifa(Float tarifa) {
        this.tarifa = tarifa;
    }

    public String getDocumentacion() {
        return this.documentacion;
    }

    public void setDocumentacion(String documentacion) {
        this.documentacion = documentacion;
    }

    public Integer getPanchoPuntos() {
        return this.panchoPuntos;
    }

    public void setPanchoPuntos(Integer panchoPuntos) {
        this.panchoPuntos = panchoPuntos;
    }

    public String getIBAN() {
        return this.IBAN;
    }

    public void setIBAN(String IBAN) {
        this.IBAN = IBAN;
    }

    public String getFoto() {
        return this.foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public void agregarDueno(Dueno dueno) {
        this.duenos.add(dueno);
    }

    public void agregarMascota(Mascota mascota) {
        this.mascotas.add(mascota);
    }

    public void agregarMascotaExotica(MascotaExotica mascotaExotica) {
        this.mascotaExoticas.add(mascotaExotica);

    }

    @Override
    public String toString() {
        return "Cuidador{" +
                "nombre=" + this.getNombre() +
                ", email=" + this.getEmail() +
                ", contrasenia=" + this.getContrasenia() +
                ", direccion=" + this.getDireccion() +
                ", descripcion=" + this.descripcion +
                ", distanciaMax=" + this.distanciaMax +
                ", tarifa=" + this.tarifa +
                ", documentacion=" + this.documentacion +
                ", IBAN=" + this.IBAN +
                ", foto=" + this.foto +
                ", mascotas=" + this.mascotas +
                '}';
    }

    public boolean aceptarEngargo() {

        return false;
    }

    public boolean rechazarEncargo() {

        return false;
    }
}
