//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : CuidandoAPancho.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class CuidandoAPancho {
	private void CifrarContrasenia() {
	
	}
}
