//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Due�o.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


import java.util.ArrayList;
import java.util.List;

public class Dueno extends Usuario {
	private List<Mascota> mascotas;
	private List<MascotaExotica> mascotasExoticas;
	private List<Cuidador> cuidadores;


	public Dueno(Integer id, String nombre, String email, String contrasenia, String direccion){
		super(id, nombre, email, contrasenia, direccion);
		this.mascotas=new ArrayList<>();
		this.mascotasExoticas=new ArrayList<>();
		this.cuidadores=new ArrayList<>();
	}

	public Dueno(String nombre,String email,String contrasenia,String direccion){
		super(nombre,email,contrasenia,direccion);
		this.mascotas=new ArrayList<>();
		this.mascotasExoticas=new ArrayList<>();
		this.cuidadores=new ArrayList<>();
	}
	//Codificar
	public void agregarMascota(Mascota mascota) {
	this.mascotas.add(mascota);
	}

	public void eliminarMascota(Mascota mascota) {
		if (this.mascotas.contains(mascota)) {
			this.mascotas.remove(mascota);
		}
	}
	public void agregarMascotaExotica(MascotaExotica mascotaExotica) {
	this.mascotasExoticas.add(mascotaExotica);
	}

	public void eliminarMascotaExotica(MascotaExotica mascotaExotica) {
		if (this.mascotas.contains(mascotaExotica)) {
			this.mascotas.remove(mascotaExotica);
		}
	}
	public void agregarCuidador(Cuidador cuidador){
		this.cuidadores.add(cuidador);

	}
	public List<Mascota> getMascotas() {
		return this.mascotas;
	}

	public void setMascotas(List<Mascota> mascotas) {
		this.mascotas = mascotas;
	}

	public List<MascotaExotica> getMascotasExoticas() {
		return this.mascotasExoticas;
	}

	public void setMascotasExoticas(List<MascotaExotica> mascotasExoticas) {
		this.mascotasExoticas = mascotasExoticas;
	}

	public List<Cuidador> getCuidadoresFavoritos() {
		return this.cuidadores;
	}

	public void setCuidadores(List<Cuidador> cuidadores) {
		this.cuidadores = cuidadores;
	}
	@Override
	public String toString() {
		return "Dueno{" +
				"nombre=" + this.nombre +
				", email=" + this.email +
				", contrasenia=" + this.contrasenia  +
				", direccion=" + this.direccion  +
				'}';
	}

	public void contratarCuidador() {

	}
	
	public void rescindirCuidador() {
	
	}
	
	public void encontrarCuidador() {
	
	}
	
	public void listarCuidadores() {
	
	}
	
	public void cambiarParametroMascota() {
	
	}
}
