//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Foto.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class Foto {
	private String id;
	private String fichero;
	public Album esContenido;
	public Foto(String id ,String fichero) {
		this.id=id;
		this.fichero=fichero;
	
	}
	public String getId(){return this.id;}

	public void setId(String id) {
		this.id = id;
	}

	public String getFichero() {
	return this.fichero;
	}
	
	public void setFichero(String fichero) {
	this.fichero=fichero;
	}
}
