//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : HistorialPremios.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class HistorialPremios {
	private Object productosEntregados;
}
