//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : ListaCuidadoresFavoritos.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class ListaCuidadoresFavoritos {
	private Object id;

}
