//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : ListaMascotasACargo.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class ListaMascotasACargo {
}
