//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Mascota Ex�tica.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class MascotaExotica extends Mascota {
    private String certificadoProcedencia;
    private String certificadoSalud;
    private String permisoLegal;

    public MascotaExotica(Long codigoRIAC, String nombre, String descripcion, String direccion, Integer nPoliza, String tipo, String certificadoProcedencia, String certificadoSalud, String permisoLegal) {
        super(codigoRIAC, nombre, descripcion, direccion, nPoliza, tipo);
        this.certificadoProcedencia = certificadoProcedencia;
        this.certificadoSalud = certificadoSalud;
        this.permisoLegal = permisoLegal;

    }

    public String getCertificadoProcedencia() {
        return this.certificadoProcedencia;
    }

    public void setCertificadoProcedencia(String certificadoProcedencia) {
        this.certificadoProcedencia = certificadoProcedencia;
    }

    public String getCertificadoSalud() {
        return this.certificadoSalud;
    }

    public void setCertificadoSalud(String certificadoSalud) {
        this.certificadoSalud = certificadoSalud;
    }

    public String getPermisoLegal() {
        return this.permisoLegal;
    }

    public void setPermisoLegal(String permisoLegal) {
        this.permisoLegal = permisoLegal;
    }

    @Override
    public String toString() {
        return "MascotaExotica{" +
                "codigoRIAC=" + this.getCodigoRIAC() +
                ", nombre=" + this.getNombre() +
                ", descripcion=" + this.getDescripcion() + '\'' +
                ", direccion=" + this.getDireccion() +
                ", nPoliza=" + this.getNPoliza() +
                ", tipo=" + this.getTipo() +
                ", certificadoProcedencia=" + this.certificadoProcedencia +
                ", certificadoSalud=" + this.certificadoSalud +
                ", permisoLegal=" + this.permisoLegal +
                '}';
    }


}
