//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Mascota.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Mascota {
    private String nombre;
    private String descripcion;
    private String direccion;
    private Integer nPoliza;
    private Long codigoRIAC;
    private String tipo;

    public Mascota(Long codigoRIAC, String nombre, String descripcion, String direccion, Integer nPoliza, String tipo) {
        this.codigoRIAC = codigoRIAC;
        this.nombre = nombre;
        this.direccion = direccion;
        this.descripcion = descripcion;
        this.nPoliza = nPoliza;
        this.tipo = tipo;
    }


    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getNPoliza() {
        return this.nPoliza;
    }

    public void setNPoliza(Integer npoliza) {
        this.nPoliza = npoliza;
    }

    public Long getCodigoRIAC() {
        return this.codigoRIAC;
    }

    public void setCodigoRIAC(Long codigoRIAC) {
        this.codigoRIAC = codigoRIAC;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Override
    public String toString() {
        return "Mascota{" +
                "codigoRIAC=" + this.codigoRIAC +
                ", nombre=" + this.nombre +
                ", descripcion=" + this.descripcion +
                ", direccion=" + this.direccion +
                ", nPoliza=" + this.nPoliza +
                ", tipo=" + this.tipo +
                '}';
    }

    public Integer getnPoliza() {
        return this.nPoliza;
    }
}
