//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Mensaje.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Mensaje {
    public Oferta incuye;
    private String id;
    private String fecha;
    private String texto;
    private Boolean leido;

    //Cambiar el constructor en el diagrama de clases
    public Mensaje(String texto, String fecha, Boolean leido) {
        this.texto = texto;
        this.fecha = fecha;
        this.leido = leido;
    }

    public String getFecha() {
        return this.fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public Boolean getLeido() {
        return this.leido;
    }

    public void setLeido(Boolean leido) {
        this.leido = leido;
    }
}
