//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Notificacion.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//



package DiagramaDeClases;


public class Notificacion {
	private String id;
	private String fechaLectura;
	public Cuidado notifica;
	public Notificacion(String fechaLectura) {
		this.fechaLectura=fechaLectura;
	
	}
	
	public String getFechaLectura() {
	return this.fechaLectura;
	}
	
	public void setFechaLectura(String fechaLectura) {
	this.fechaLectura=fechaLectura;
	}
}
