//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Oferta.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Oferta {
    public Mensaje esIncuilda;
    private String id;
    private EstadoOferta estado;
public Oferta(String id,Mensaje esIncuilda,EstadoOferta estado){
	this.id = id;
	this.esIncuilda=esIncuilda;
	this.estado=estado;
}
    public EstadoOferta getEstado() {
        return this.estado;
    }

    public void setEstado(EstadoOferta estado) {
		this.estado=estado;

    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Mensaje getEsIncuilda() {
        return esIncuilda;
    }

    public void setEsIncuilda(Mensaje esIncuilda) {
        this.esIncuilda = esIncuilda;
    }
}
