//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Pago.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Pago {
    private Object id;
    private Object fechadepagado;
    private Object fechadeimporte;

}
