//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Premios.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


import java.util.List;

public class Premios {
    private Integer id;
    private Integer coste;
    private String fechaCompra;
    private List<Cuidador> cuidadores;

    public Premios(Integer id, Integer coste, String fechaCompra) {
        this.id = id;
        this.coste = coste;
        this.fechaCompra = fechaCompra;

    }

    public Premios(Integer coste, String fechaCompra) {
        this(null, coste, fechaCompra);

    }

    public Integer getCoste() {
        return this.coste;
    }

    public void setCoste(Integer coste) {
        this.coste = coste;
    }

    public String getFechaCompra() {
        return this.fechaCompra;
    }

    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public List<Cuidador> getCuidadores() {
        return cuidadores;
    }

    public void setCuidadores(List<Cuidador> cuidadores) {
        this.cuidadores = cuidadores;
    }

}
