//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Producto.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Producto extends Premios {
    private String nombre;
    private String descripcion;

    public Producto(Integer coste, String fechaCompra, String nombre, String descripcion) {
        super(coste, fechaCompra);
        this.nombre = nombre;
        this.descripcion = descripcion;

    }

    public String getNombre() {
        return this.nombre = nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion = descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
