//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Promoci�n.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Promocion extends Premios {
    private String fechaInicio;
    private String fechaFin;

    public Promocion(Integer coste, String fechaCompra, String fechaInicio, String fechaFin) {
        super(coste, fechaCompra);
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;

    }

    public String getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public String getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }
}
