//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : CuidandoAPancho
//  @ File Name : Usuario.java
//  @ Date : 03/05/2024
//  @ Author : 
//
//


package DiagramaDeClases;


public class Usuario {
    public Mensaje emite;
    public Mensaje recibe;
    protected Integer id;
    String nombre;
    String email;
    String contrasenia;
    String direccion;
    private TipoProveedor oauth_proveedor;
    private String oauth_id;
    private EnumIdioma idioma;

    public Usuario(Integer id, String nombre, String email, String contrasenia, String direccion) {
        this.id = id;
        this.nombre = nombre;
        this.email = email;
        this.contrasenia = contrasenia;
        this.direccion = direccion;
    }

    public Usuario(String nombre, String email, String contrasenia, String direccion) {
        this(null, nombre, email, contrasenia, direccion);
    }


    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {//No hace falta(revisar)
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContrasenia() {
        return this.contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }


    public TipoProveedor getOauth_Proveedor() {
        return oauth_proveedor;

    }

    public void setOauth_proveedor(TipoProveedor oauth_proveedor) {
        this.oauth_proveedor = oauth_proveedor;
    }

    public String getOauth_id() {
        return oauth_id;
    }

    public void setOauth_id(String oauth_id) {
        this.oauth_id = oauth_id;
    }

    public EnumIdioma getIdioma() {
        return idioma;
    }

    public void setIdioma(EnumIdioma idioma) {
        this.idioma = idioma;
    }

    public Mensaje getEmite() {
        return emite;
    }

    public void setEmite(Mensaje emite) {
        this.emite = emite;
    }

    public Mensaje getRecibe() {
        return recibe;
    }

    public void setRecibe(Mensaje recibe) {
        this.recibe = recibe;
    }
}
